<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-5PQG68E" failures="1" tests="1" name="Default test" time="84.888" errors="0" timestamp="2022-10-26T18:51:38 IST">
  <testcase classname="com.supermarket.tests.ManageDeliveryBoyTest" name="delete_ManageDeliveryBoyData" time="10.596">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	The type java.util.Iterator cannot be resolved. It is indirectly referenced from required .class files
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
The type java.util.Iterator cannot be resolved. It is indirectly referenced from required .class files

at com.supermarket.utilities.GeneralUtility.<init>(GeneralUtility.java:1)
at com.supermarket.pages.ManageDeliveryBoy.deleteDeliveryBoyData(ManageDeliveryBoy.java:139)
at com.supermarket.tests.ManageDeliveryBoyTest.delete_ManageDeliveryBoyData(ManageDeliveryBoyTest.java:74)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- delete_ManageDeliveryBoyData -->
  <testcase classname="com.supermarket.tests.ManageDeliveryBoyTest" name="create_DeliveryBoyData" time="0.0">
    <ignored/>
  </testcase> <!-- create_DeliveryBoyData -->
  <testcase classname="com.supermarket.tests.ManageDeliveryBoyTest" name="verify_ManageDeliveryBoyTextAlertMessage" time="0.0">
    <ignored/>
  </testcase> <!-- verify_ManageDeliveryBoyTextAlertMessage -->
</testsuite> <!-- Default test -->
